# Generated by Django 3.0.7 on 2020-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_One', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
