# Generated by Django 3.0.7 on 2020-06-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_One', '0002_book_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
